### ISSUE TITLE
Rails 5 Compatibility

### ISSUE THREAD

**Issue by escowles** [pulibrary/pul_uv_rails#1]
When compiling assets for staging/production environments, I see errors if I have serving assets disabled (the default since it's assumed Apache or Nginx will serve them):

```
No such middleware to insert before: ActionDispatch::Static
```

So I suspect this needs to be updated: https://github.com/pulibrary/pul_uv_rails/blob/master/lib/pul_uv_rails.rb#L7

**Comment by jrgriffiniii** [comment]
This was found to block https://github.com/pulibrary/pulmap/pull/378
